### ISSUE TITLE
What happened to pyload.org? It seems down

### ISSUE THREAD

**Issue by timofonic** [pyload/pyload.github.io#1]
Hello.

I can't access to PyLoad.org but pyload.github.io works.

http://www.downforeveryoneorjustme.com/pyload.org
http://www.downforeveryoneorjustme.com/www.pyload.org

What happened?

Traceroute is weird...
https://who.is/tools/traceroute/pyload.org/

Kind regards.

**Comment by vuolter** [comment]
Server has expired.
Soon pyload.org will redirect to pyload.github.io .

**Comment by Jonn3y** [comment]
Any news here? Doesn't look like pyload.org will be online again :/ Maybe I could create a new one .
